# Generated by Django 5.1.2 on 2025-06-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentlogincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='login_roles/')),
            ],
        ),
    ]
