# Generated by Django 5.1.2 on 2025-06-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_loginrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
