# Generated by Django 5.1.2 on 2025-06-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sprite',
            field=models.ImageField(blank=True, null=True, upload_to='sprites/'),
        ),
    ]
