# Generated by Django 5.1.2 on 2025-06-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='league',
            field=models.CharField(choices=[('Stone', 'Stone'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Emerald', 'Emerald'), ('Sapphire', 'Sapphire'), ('Ruby', 'Ruby'), ('Diamond', 'Diamond'), ('Amethyst', 'Amethyst'), ('Obsidian', 'Obsidian')], default='Stone', max_length=20),
        ),
    ]
