# Generated by Django 5.2.5 on 2026-03-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_course_description'),
        ('users', '0012_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='subscribed_profiles', to='blog.course'),
        ),
    ]
