# Generated by Django 5.2.5 on 2026-03-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='template_data',
            field=models.TextField(blank=True, default='', help_text='Enter one value per line, or a JSON array like ["a","b","c"].'),
        ),
        migrations.AddField(
            model_name='task',
            name='template_type',
            field=models.CharField(choices=[('none', 'None'), ('reorder', 'Reorder (drag to correct order)'), ('random_click', 'Random Click (pick randomized value)'), ('placeholder1', 'Placeholder 1'), ('placeholder2', 'Placeholder 2')], default='none', max_length=50),
        ),
    ]
