# Generated by Django 5.2.5 on 2026-03-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_task_template_data_task_template_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='grades', to='blog.course')),
            ],
        ),
    ]
