# Generated by Django 5.2.5 on 2026-04-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('mission', 'Mission'), ('team', 'Team'), ('career', 'Career'), ('contact', 'Contact'), ('faq', 'FAQ')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=False, help_text='Mark this item as the current/active one for this section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.sitesectionitem',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.sitesectionitem',),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.sitesectionitem',),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.sitesectionitem',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.sitesectionitem',),
        ),
    ]
