# Generated by Django 5.2.5 on 2026-04-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_game_sitesectionitem_career_contact_faq_mission_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
