# Generated by Django 5.2.5 on 2026-04-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_career_delete_contact_delete_faq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='template_name',
            field=models.CharField(choices=[('none', 'None'), ('ball_drop', 'Ball Drop'), ('number_pop', 'Number Pop')], default='none', max_length=50),
        ),
    ]
