# Generated by Django 5.2.5 on 2026-04-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_game_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('asset_type', models.CharField(choices=[('item', 'Item'), ('ground', 'Ground')], default='item', max_length=20)),
                ('image', models.ImageField(upload_to='game_assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, help_text='Optional: associate asset with a specific Game', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='blog.game')),
            ],
        ),
    ]
