# Generated by Django 5.2.5 on 2026-04-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_gameasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='out_of_order',
            field=models.BooleanField(default=False, help_text='Mark game as temporarily unavailable'),
        ),
    ]
