# Generated by Django 5.2.5 on 2026-05-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_questcategory_questpage_quest_completedquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='overlay_3d',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='overlay_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='blue', max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='overlay_items',
            field=models.TextField(blank=True, default='', help_text='Enter one item per line to display on the course background.'),
        ),
    ]
