# Generated by Django 5.2.5 on 2026-07-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_course_overlay_3d_course_overlay_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('lesson_titles', models.TextField(blank=True, default='', help_text='Add one lesson title per line.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
