# Generated by Django 5.2.5 on 2026-07-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_lessonpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='finish_date',
            field=models.DateTimeField(blank=True, help_text='The date when students should finish this lesson.', null=True),
        ),
    ]
