# Generated by Django 5.2.5 on 2026-07-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_lesson_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide this lesson from lesson planners and teacher views when completed.'),
        ),
    ]
