# Generated by Django 5.2.5 on 2026-04-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0013_delete_career_delete_contact_delete_faq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.sitesectionitem',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.sitesectionitem',),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.sitesectionitem',),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.sitesectionitem',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.sitesectionitem',),
        ),
    ]
